### ISSUE TITLE
No GUI with version 2.5

### ISSUE THREAD

**Issue by lazaj** [teiram/dandanator-cpc#3]
Hello,

I try to launch version 2.5, but no GUI shows up.
I've downloaded jar file from http://www.dandare.es/ no GUI.
I've built it from source, no GUI.

I tried it on OSX, Windows & Linux same result.

Version 2.4 from http://www.dandare.es/ work fine.

java -jar dandanator-cpc-2.5-jar-with-dependencies.jar
35 [JavaFX Application Thread] WARN LocaleUtil - Loading language bundle for locale fr_FR
java.util.MissingResourceException: Can't find bundle for base name romgenerator, locale fr_FR
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:899)
	at com.grelobites.romgenerator.util.LocaleUtil.getBundle(LocaleUtil.java:31)
	at com.grelobites.romgenerator.util.LocaleUtil.i18n(LocaleUtil.java:43)
	at com.grelobites.romgenerator.ApplicationContext.<init>(ApplicationContext.java:97)
	at com.grelobites.romgenerator.ApplicationContext.getInstance(ApplicationContext.java:85)
	at com.grelobites.romgenerator.MainApp.initRootLayout(MainApp.java:324)
	at com.grelobites.romgenerator.MainApp.start(MainApp.java:169)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
36 [JavaFX Application Thread] WARN LocaleUtil - Defaulting to English
88 [JavaFX Application Thread] DEBUG PreferencesProvider - Adding preferences provider PreferencesProvider{name='General', fXmlLocation='/com/grelobites/romgenerator/view/preferences.fxml', precedence=1}
88 [JavaFX Application Thread] DEBUG PreferencesProvider - Adding preferences provider PreferencesProvider{name='Loader', fXmlLocation='/com/grelobites/romgenerator/view/eepromwriterconfiguration.fxml', precedence=3}
javafx.fxml.LoadException: Resource "gameAutobootColumn" not found.
file:/Users/julien/Documents/dandanator-cpc/target/dandanator-cpc-2.5-jar-with-dependencies.jar!/com/grelobites/romgenerator/view/mainapp.fxml:49

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2597)
	at javafx.fxml.FXMLLoader.access$100(FXMLLoader.java:103)
	at javafx.fxml.FXMLLoader$Element.resolvePrefixedValue(FXMLLoader.java:424)
	at javafx.fxml.FXMLLoader$Element.processValue(FXMLLoader.java:363)
	at javafx.fxml.FXMLLoader$Element.processPropertyAttribute(FXMLLoader.java:325)
	at javafx.fxml.FXMLLoader$Element.processInstancePropertyAttributes(FXMLLoader.java:235)
	at javafx.fxml.FXMLLoader$ValueElement.processEndElement(FXMLLoader.java:767)
	at javafx.fxml.FXMLLoader.processEndElement(FXMLLoader.java:2823)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2532)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at com.grelobites.romgenerator.MainApp.getApplicationPane(MainApp.java:319)
	at com.grelobites.romgenerator.MainApp.initRootLayout(MainApp.java:339)
	at com.grelobites.romgenerator.MainApp.start(MainApp.java:169)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by teiram** [comment]
Hi @lazaj,
there was an issue with the translation files. Should be corrected now (uploaded also to dandare.es)
BR Manuel
