### ISSUE TITLE
Unable to send 

### ISSUE THREAD

**Issue by andymccall** [teiram/dandanator-cpc#6]
Hi,

I'm have a hard time getting anything sent to my CPC Dandanator Mini.  I admit that this is most likely due to my OS rather than the software, but I was hoping someone could help all the same.

**ROMSet Loading**

When trying to send a romset to the device it looks like it's sending a block, but it never passes 1/32, nothing changes on the CPC's Loader screen and the following logs seems to loop through the following on the console:

```297024 [JavaFX Application Thread] DEBUG EepromWriterController - Unbinding data producer
297523 [SerialBlockService] DEBUG SerialPortConfiguration - Applying serial port configuration SerialPortConfiguration{baudrate=57600, dataBits=8, stopBits=2, parity=0}
297523 [SerialBlockService] DEBUG SerialBlockService - Block 0 Requested by serial port
297525 [SerialBlockService] DEBUG SerialPortConfiguration - Applying serial port configuration SerialPortConfiguration{baudrate=114000, dataBits=8, stopBits=2, parity=0}
297525 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
297525 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
297525 [JavaFX Application Thread] DEBUG EepromWriterController - Binding data producer com.grelobites.romgenerator.util.eewriter.SerialDataProducer@74bef715
297525 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
297607 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
297802 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
297998 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
298193 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
298388 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
298583 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
298778 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
298974 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
299169 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
299364 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
299559 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
299754 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
299950 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
300145 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 3 bytes
300146 [JavaFX Application Thread] DEBUG EepromWriterController - Unbinding data producer
300645 [SerialBlockService] DEBUG SerialPortConfiguration - Applying serial port configuration SerialPortConfiguration{baudrate=57600, dataBits=8, stopBits=2, parity=0}
300646 [SerialBlockService] DEBUG SerialBlockService - Block 0 Requested by serial port
300647 [SerialBlockService] DEBUG SerialPortConfiguration - Applying serial port configuration SerialPortConfiguration{baudrate=114000, dataBits=8, stopBits=2, parity=0}
300647 [SerialBlockService] DEBUG SerialDataProducer - Sending block of 1024 bytes
300647 [JavaFX Application Thread] DEBUG EepromWriterController - Binding data producer com.grelobites.romgenerator.util.eewriter.SerialDataProducer@1f94dd1a
```

**USB Game Loading**

When trying to send a game via USB, I place the CPC Dandanator Mini into USB Game mode by pressing U, then send a game.  I get the following in the console:

```22736 [RomGenerator executor service] DEBUG SerialPortConfiguration - Applying serial port configuration SerialPortConfiguration{baudrate=57600, dataBits=8, stopBits=2, parity=0}
27738 [RomGenerator executor service] ERROR SerialGameUploader - Transferring Game
jssc.SerialPortTimeoutException: Port name - /dev/ttyUSB0; Method name - readBytes(); Serial port operation timeout (5000 ms).
        at jssc.SerialPort.waitBytesWithTimeout(SerialPort.java:567)
        at jssc.SerialPort.readBytes(SerialPort.java:586)
        at com.grelobites.romgenerator.util.SerialGameUploader.run(SerialGameUploader.java:133)
        at com.grelobites.romgenerator.handlers.dandanatorcpc.v2.DandanatorCpcV2RomSetHandler.lambda$null$10(DandanatorCpcV2RomSetHandler.java:847)
        at com.grelobites.romgenerator.ApplicationContext$BackgroundTask.call(ApplicationContext.java:329)
        at com.grelobites.romgenerator.ApplicationContext$BackgroundTask.call(ApplicationContext.java:312)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```
        
**Java**

```andymccall@earth:~/Downloads$ java -version
java version "1.8.0_421"
Java(TM) SE Runtime Environment (build 1.8.0_421-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.421-b09, mixed mode
```

**lsusb**

```andymccall@earth:~/Downloads$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 024: ID 1a86:7523 QinHeng Electronics CH340 serial converter
Bus 001 Device 002: ID 1532:0e03 Razer USA, Ltd Gaming Webcam [Kiyo]
Bus 001 Device 005: ID 1532:0099 Razer USA, Ltd Razer Basilisk V3
Bus 001 Device 004: ID 1532:025d Razer USA, Ltd RZ03-0338, Gaming Keyboard [Ornata V2]
Bus 001 Device 003: ID 8087:0a2b Intel Corp. Bluetooth wireless interface
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Permissions**

```andymccall@earth:~/Downloads$ ls -la /dev/ttyUSB*
crw-rw---- 1 root dialout 188, 0 Aug 11 12:46 /dev/ttyUSB0```

```andymccall@earth:~/Downloads$ groups
andymccall adm dialout cdrom sudo dip plugdev lpadmin sambashare
```

**Java**

```andymccall@earth:~/Downloads$ echo $JAVA_HOME
/home/andymccall/Downloads/jre1.8.0_421/lib
```

I'm using KDE Neon, but I don't think that makes too much difference for Java and Linux.

Please help!

**Comment by teiram** [comment]
Hi @andymccall 
The romset update procedure seems to show that the CPC keeps asking for block 0 endlessly. On the other side, your attempt to upload a game seems to timeout while trying to read data coming from the CPC side. This is somehow weird since I would expect timeouts in both usecases, but on the romset update seems to keep receiving a request for block zero whereas on the game upload seems to just timeout...
My first idea would be to validate the hardware. Have you been able to validate that the serial port works by some other means so that we can discard a hardware issue? Did you assemble the device yourself or got it from some 3rd party provider? Maybe you could upload a photo of the device board to see if it could give us any hint?

**Comment by andymccall** [comment]
Hi Teiram - thank you for replying.

I bought the device from eBay. I'd probably be capable of building one myself as I've recently up'd my electronics skills, but for ease I just bought one.  It's already been programmed with a set of freeware games on it, so it must have been capable of being written to at some ponit.

Here's some pictures of the PCB.  It came in a nice 3D printed case, so I've opened it up and everythign seems in order.

https://imgur.com/a/laGvqKf

Can I check - does the CPC have anything to do with the device other than powering it?  I've got 2x464's and 1x6128's here, and I haven't tested on another machine as I didn't think that would make a difference, I thought the issue was between my desktop PC, the cable and the CPC Dandanator Mini.  I can try on the 464 if that rules out the 6128. It might be a dodgy connector or something.

**Comment by andymccall** [comment]
On my CPC6128 I gave the connector a really good clean until it was nice and shiny on both sides. I also tried on a CPC464, and got exactly the same behaviour, so I think I can rule out the Amstrad devices.  It's almost certainly the OS/Linux, Java and the Dandanator ROM generator.  I was thinking of putting something like VirtualBox on my machine and installing Windows in it and seeing if I can send via a Windows machine.

I did seem to be able to progress with sending via USB, I actually got the machine to recognise the remote machine, but it fails with the following:

```
39020 [JavaFX Application Thread] DEBUG SnapshotGame - Screen page is c000
39020 [JavaFX Application Thread] DEBUG SnapshotGame - Index in peripheral configuration is 3, current RAM configuration is 192
39020 [JavaFX Application Thread] DEBUG SnapshotGame - Getting screenshot from slot 3 with offset 0
39023 [JavaFX Application Thread] DEBUG ImageUtil - scrLoader with screenMode 1, crtcDisplayData CrtcDisplayData{visibleWidth=32, visibleHeight=20, displayOffset=0}
42794 [RomGenerator executor service] DEBUG SerialPortConfiguration - Applying serial port configuration SerialPortConfiguration{baudrate=57600, dataBits=8, stopBits=2, parity=0}
46155 [RomGenerator executor service] DEBUG SerialGameUploader - Got command bytes [0xFF ]
46155 [RomGenerator executor service] DEBUG SerialGameUploader - Sending slot  screen + code
46157 [RomGenerator executor service] DEBUG SnapshotGame - Screen page is c000
46157 [RomGenerator executor service] DEBUG SnapshotGame - Index in peripheral configuration is 3, current RAM configuration is 192
46157 [RomGenerator executor service] DEBUG SerialGameUploader - Sending block of data with length 17111
46157 [RomGenerator executor service] DEBUG SerialPortConfiguration - Applying serial port configuration SerialPortConfiguration{baudrate=114000, dataBits=8, stopBits=2, parity=0}
46157 [RomGenerator executor service] DEBUG SerialGameUploader - Sending block of 2048 bytes
46158 [RomGenerator executor service] DEBUG SerialGameUploader - Sending block of 2048 bytes
46158 [RomGenerator executor service] DEBUG SerialGameUploader - Sending block of 2048 bytes
46524 [RomGenerator executor service] DEBUG SerialGameUploader - Sending block of 2048 bytes
46914 [RomGenerator executor service] DEBUG SerialGameUploader - Sending block of 2048 bytes
47305 [RomGenerator executor service] DEBUG SerialGameUploader - Sending block of 2048 bytes
47695 [RomGenerator executor service] DEBUG SerialGameUploader - Sending block of 2048 bytes
48086 [RomGenerator executor service] DEBUG SerialGameUploader - Sending block of 2048 bytes
48476 [RomGenerator executor service] DEBUG SerialGameUploader - Sending block of 727 bytes
49117 [RomGenerator executor service] DEBUG SerialPortConfiguration - Applying serial port configuration SerialPortConfiguration{baudrate=57600, dataBits=8, stopBits=2, parity=0}
59118 [RomGenerator executor service] ERROR SerialGameUploader - Transferring Game
jssc.SerialPortTimeoutException: Port name - /dev/ttyUSB0; Method name - readBytes(); Serial port operation timeout (10000 ms).
        at jssc.SerialPort.waitBytesWithTimeout(SerialPort.java:567)
        at jssc.SerialPort.readBytes(SerialPort.java:586)
        at com.grelobites.romgenerator.util.SerialGameUploader.run(SerialGameUploader.java:133)
        at com.grelobites.romgenerator.handlers.dandanatorcpc.v2.DandanatorCpcV2RomSetHandler.lambda$null$10(DandanatorCpcV2RomSetHandler.java:847)
        at com.grelobites.romgenerator.ApplicationContext$BackgroundTask.call(ApplicationContext.java:329)
        at com.grelobites.romgenerator.ApplicationContext$BackgroundTask.call(ApplicationContext.java:312)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```
I suspect it's something to do with Linux, Java and serial operations that are failing.

**Comment by teiram** [comment]
Yes, the CPC is relevant in the firmware upgrade and/or game upload. The CPC is constantly controlling what the CPC Dandanator does by issuing special opcodes that are captured by the Dandanator to do specific tasks (switching memory banks, copying from the serial port,, reading from the EEPROM...). Take into account that the CPC Dandanator has no CPU on its own, just a CPLD to read opcodes from the data bus and react to them by switching banks or intercepting Z80 data requests to provide data from the built-in EEPROM. The firmware upgrade is in fact a program running on the CPC that instructs the CPC Dandanator to send the proper command sequences via the serial port for the ROM Generator.
 
If you tried with different computers and you have the same results, it must be a problem elsewhere.

It came to my mind that there were some changes in the serial protocol through the different versions, some related to the serial  upload and download speed (you might have noticed the speed is not the same during upload and download), but it was years ago and don't remember exactly the details now. It might be the protocol is not the expected one.
Could you please check what is the current version of the firmware installed in your dandanator device? It should show on the CPC computer screen somewhere in the menu. I will anyways try to find the time to give it a try with a linux computer and one of my devices.

**Comment by andymccall** [comment]
It says V2.5.  I'll look to see if there's an update somewhere.

**Comment by teiram** [comment]
I tried it myself from linux and run into similar issues. Trying to load a game via USB I get garbage on the CPC screen and it eventually hangs, leading to the timeout on the PC side. I have made a small modification in the transfer speed and it works for me at least. Please try with the version I'm attaching here and let me know how it goes:
[dandanator-cpc-2.6.1.zip](https://github.com/user-attachments/files/16679946/dandanator-cpc-2.6.1.zip)
Just rename the zip to jar and you are good to go. This version should run up on a JRE up to java 17 and already includes the javafx libraries. it should still work with java8 if I'm not mistaken but the stock java version bundled with your linux distribution should also suffice.

**Comment by iwanttobefreak** [comment]
> I tried it myself from linux and run into similar issues. Trying to load a game via USB I get garbage on the CPC screen and it eventually hangs, leading to the timeout on the PC side. I have made a small modification in the transfer speed and it works for me at least. Please try with the version I'm attaching here and let me know how it goes: [dandanator-cpc-2.6.1.zip](https://github.com/user-attachments/files/16679946/dandanator-cpc-2.6.1.zip) Just rename the zip to jar and you are good to go. This version should run up on a JRE up to java 17 and already includes the javafx libraries. it should still work with java8 if I'm not mistaken but the stock java version bundled with your linux distribution should also suffice.

Hello teiram. I have the same problem with linux. I have test your new version and works fine. A lot of thanks
Can you apply the changes in master branch?
Thanks!

**Comment by teiram** [comment]
Hello @iwanttobefreak 
I applied the changes to the master branch.
BR Manuel
