### ISSUE TITLE
New compiled releases?

### ISSUE THREAD

**Issue by hecspc** [teiram/dandanator-cpc#7]
Hi,
I can't see that the code is updated and currently the version is the 2.6.x but in the releases it is only up to 2.0 from 2019.

Im on Mac computer with M2 and unfortunately the 2.0 version is not ready for this architecture and the serial library fails.

I found on other issue a link to download a compiled version of 2.6.1 and the serial library works (I can open the loader tab in the preferences and select the serial port) but it fails when try to open the writer clicking on the black circle.

Is there a place where we can download the latest binaries for the different architectures?

Here is the full stack

```
Exception in thread "JavaFX Application Thread" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at com.grelobites.romgenerator.util.tape.BinaryRecordIterator.next(BinaryRecordIterator.java:73)
        at com.grelobites.romgenerator.util.tape.CdtBuilder.addBinary(CdtBuilder.java:42)
        at com.grelobites.romgenerator.util.player.AudioDataPlayerSupport.getRescueLoaderAudioFile(AudioDataPlayerSupport.java:44)
        at com.grelobites.romgenerator.util.player.SampledAudioDataPlayer.<init>(SampledAudioDataPlayer.java:51)
        at com.grelobites.romgenerator.view.EepromWriterController.<init>(EepromWriterController.java:153)
        at com.grelobites.romgenerator.view.MainAppController.getEepromWriterController(MainAppController.java:464)
        at com.grelobites.romgenerator.view.MainAppController.getEepromWriterPane(MainAppController.java:474)
        at com.grelobites.romgenerator.view.MainAppController.lambda$initialize$4(MainAppController.java:218)
        at com.sun.javafx.scene.control.skin.PaginationSkin.createPage(PaginationSkin.java:329)
        at com.sun.javafx.scene.control.skin.PaginationSkin.animateSwitchPage(PaginationSkin.java:388)
        at com.sun.javafx.scene.control.skin.PaginationSkin.access$500(PaginationSkin.java:74)
        at com.sun.javafx.scene.control.skin.PaginationSkin$NavigationControl.lambda$initializeNavigationHandlers$8(PaginationSkin.java:816)
        at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.beans.property.IntegerPropertyBase.fireValueChangedEvent(IntegerPropertyBase.java:106)
        at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
        at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:147)
        at javafx.scene.control.Pagination.setCurrentPageIndex(Pagination.java:269)
        at com.sun.javafx.scene.control.skin.PaginationSkin$IndicatorButton$1.handle(PaginationSkin.java:1209)
        at com.sun.javafx.scene.control.skin.PaginationSkin$IndicatorButton$1.handle(PaginationSkin.java:1204)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Node.fireEvent(Node.java:8411)
        at javafx.scene.control.ToggleButton.fire(ToggleButton.java:256)
        at com.sun.javafx.scene.control.skin.PaginationSkin$IndicatorButton.fire(PaginationSkin.java:1254)
        at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
        at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
        at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3760)
        at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3488)
        at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1765)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2497)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
        at com.sun.glass.ui.View.notifyMouse(View.java:941)
        at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)

```

**Comment by hecspc** [comment]
I want also to add that I have tried to build the application and it fails when running `mvn install`

**Comment by hecspc** [comment]
More updates. The errors when trying to install were due to the testing. The serial port is hardcoded and it doesnt exist on macos given that error. Removing the test folder completely and running a `mvn install` works now.

But when trying to execute the recent build. I have the same error as before.

I have to mention that the downloaded version from the dandare web (http://www.dandare.es/Descargas_CPC/dandanator-cpc-2.5.jar) the view to update upload the rom works but the error is on the serial port due to an unknown architecture.

@teiram any clues here? Can I go back to any version? I can see that there are no tags or releases either :(

**Comment by teiram** [comment]
Hi. Time ago I stopped providing releases and started providing packages instead, automatically generated when a new tag reaches the master branch. You can find them in the packages section.
You might want to try the last package available there to see if it fixes your problem. I'm not confident about support for your M2 by the serial library tho. Try and let me know.

**Comment by hecspc** [comment]
Hi @teiram,
Thanks for the info. I overlooked that but now I can see the packages.

I tried to compile myself and I was able finally to do it. The problem was the mismatch version of the jdk and jre. Doing everything with java11 I was able to compile and run the application with the version 2.6.1. 

To compile successfully on macos 15.1 with a M series, clone the repo and in the directory

```sh
brew install --cask adoptopenjdk11
export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
rm -rf src/test # needed because conflict with hardcoded serial ports
rm -rf ~/.m2 target # to clean maven cache and products but not necessary
mvm install
cd target
java -jar dandanator-cpc-2.6.1.jar
```

I have today downloaded the package from your build with the same version and I got the same results.

Now when opening I can see the loader tab and the libjssc works on arm64 architecture for macos and is able to find the serial ports as expected.

But when I try to upload the rom is where it fails.

1. Upload a rom or game files
2. Click on the black circle to open the writer
3. On the CPC type L to go to the loader screen
4. On the CPC change from 00 to 01 and a tick on the progress bar is marked
5. On the computer the same. It shows 1/32 the block progressbar makes one tick and then starts over and never stops and doesnt go over there. Like restarting again
If I reset the dandanator, the computer stops so the serial communications looks to be good and there is no exceptions.

I will try to research more. For now I am using a virtual machine running windows and with the 2.5 versions works well buy with the 2.6.1 in windows 11 I have problems when I click on the black circle and the writer view never displays.

I will try to investigate a little bit more. I guess the 2.6.1 is not ready for windows 11

**Comment by teiram** [comment]
Hello @hecspc 
I've just uploaded a new version that should work better regarding serial port setup. Could you please give it a try?
